site_name: Sharded
site_url: https://docs.sharded.app/

repo_name: shardedinteractive/sharded
repo_url: https://github.com/shardedinteractive/sharded
edit_uri: edit/main/docs/

nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: "Assistant"
    code: " JetBrains Mono"

  logo: "assets/sharded_transparent.png"
  favicon: "assets/favicon.ico"

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view

plugins:
  - privacy
  - search
  - blog
  - offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - def_list
  - admonition

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

copyright: >
  Copyright &copy; 2024 - 2025 Sharded Interactive –
  <a href="#__consent">Change cookie settings</a>